/* ==========================================================================
   build-vendor.js — regenerate src/vendor.js from vendor/peerjs.min.js
   Run this only when you want to update the bundled PeerJS version.

     node build-vendor.js
   ========================================================================== */
const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, 'vendor', 'peerjs.min.js');
if (!fs.existsSync(file)) {
  console.error('vendor/peerjs.min.js not found.');
  console.error('Download it with:');
  console.error('  node -e "fetch(\'https://unpkg.com/peerjs@1.5.4/dist/peerjs.min.js\').then(r=>r.text()).then(t=>require(\'fs\').writeFileSync(\'vendor/peerjs.min.js\',t))"');
  process.exit(1);
}

let code = fs.readFileSync(file, 'utf8');
// the source map is not shipped, so drop the reference to avoid devtools noise
code = code.replace(/\/\/# sourceMappingURL=\S+\s*$/, '');

const version = (code.match(/version\s*[:=]\s*["']([\d.]+)["']/) || [])[1] || 'unknown';
const out = `/* ==========================================================================
   vendor.js — PeerJS ${version}, bundled so the game needs no CDN at runtime.
   Generated by build-vendor.js from vendor/peerjs.min.js — do not edit by hand.
   License: MIT (https://github.com/peers/peerjs)
   ========================================================================== */
${code}
`;

fs.mkdirSync(path.join(__dirname, 'src'), { recursive: true });
fs.writeFileSync(path.join(__dirname, 'src', 'vendor.js'), out, 'utf8');
console.log('✅ src/vendor.js written (' + (Buffer.byteLength(out, 'utf8') / 1024).toFixed(1) + ' KB, PeerJS ' + version + ')');
